[project]
authors = ["Ryan Oates <ryanoatsie@outlook.com>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "systems"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
anthropic = ">=0.52.0,<0.53"
openai = ">=1.82.0,<2"
pip = ">=25.1.1,<26"
matplotlib = ">=3.10.3,<4"
gradle = ">=8.11.1,<9"
